
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20140808 (SVN rev 54)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 27;
  public static final int VSTRING = 39;
  public static final int CHAR = 42;
  public static final int ASSIG = 2;
  public static final int INTEGER = 40;
  public static final int REPEAT = 18;
  public static final int LLAVEDER = 5;
  public static final int ARRAY = 44;
  public static final int FOR = 20;
  public static final int WRITE = 49;
  public static final int CORCHETEIZQ = 10;
  public static final int OPSUMA = 45;
  public static final int NOT = 33;
  public static final int AND = 34;
  public static final int OR = 32;
  public static final int BOOL = 36;
  public static final int DIV = 30;
  public static final int BEGIN = 24;
  public static final int UNTIL = 19;
  public static final int NUM = 50;
  public static final int IF = 13;
  public static final int ID = 37;
  public static final int OF = 12;
  public static final int BOOLEAN = 41;
  public static final int EOF = 0;
  public static final int PARIZQ = 6;
  public static final int error = 1;
  public static final int PROGRAM = 23;
  public static final int COMA = 8;
  public static final int VCHAR = 38;
  public static final int COMENTARIO = 29;
  public static final int MOD = 31;
  public static final int DECLARACION = 3;
  public static final int CORCHETEDER = 9;
  public static final int ELSE = 14;
  public static final int PUNTO = 11;
  public static final int READ = 48;
  public static final int TO = 21;
  public static final int WHILE = 16;
  public static final int LLAVEIZQ = 4;
  public static final int THEN = 15;
  public static final int END = 25;
  public static final int STRING = 43;
  public static final int OPLOG = 47;
  public static final int DOWNTO = 22;
  public static final int PARDER = 7;
  public static final int CIERRE = 35;
  public static final int OPMULT = 46;
  public static final int VAR = 28;
  public static final int PROCEDURE = 26;
  public static final int DO = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIG",
  "DECLARACION",
  "LLAVEIZQ",
  "LLAVEDER",
  "PARIZQ",
  "PARDER",
  "COMA",
  "CORCHETEDER",
  "CORCHETEIZQ",
  "PUNTO",
  "OF",
  "IF",
  "ELSE",
  "THEN",
  "WHILE",
  "DO",
  "REPEAT",
  "UNTIL",
  "FOR",
  "TO",
  "DOWNTO",
  "PROGRAM",
  "BEGIN",
  "END",
  "PROCEDURE",
  "FUNCTION",
  "VAR",
  "COMENTARIO",
  "DIV",
  "MOD",
  "OR",
  "NOT",
  "AND",
  "CIERRE",
  "BOOL",
  "ID",
  "VCHAR",
  "VSTRING",
  "INTEGER",
  "BOOLEAN",
  "CHAR",
  "STRING",
  "ARRAY",
  "OPSUMA",
  "OPMULT",
  "OPLOG",
  "READ",
  "WRITE",
  "NUM"
  };
}

